# Generated by Django 5.2 on 2025-04-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
